# Generated by Django 3.0.1 on 2019-12-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lol_id', models.CharField(max_length=63)),
                ('name', models.CharField(max_length=200)),
                ('icon_id', models.IntegerField()),
                ('puuid', models.CharField(max_length=78)),
                ('account_id', models.CharField(max_length=56)),
                ('level', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
