# Generated by Django 3.0.1 on 2020-01-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_request', '0002_champion_game_item_itemattribute_rune_team_teamplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='version',
            field=models.CharField(max_length=50),
        ),
    ]
